---
- name: Install python docker module
  become: true
  package:
    name: python-docker
    state: present

- name: Create network
  docker_network:
    name: "{{ frontend_network }}"

- name: Create frontend container
  docker_container:
    name: frontend
    image: "fadalax/frontend:v0.0.2"
    restart_policy: always
    pull: yes
    networks:
      - name:  "{{ frontend_network }}"
    env:
