---
- name: install xfce
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - xfce4
    - firefox-esr

- name: create user
  become: true
  user: 
    name: client 
    password: $1$salt$rQp0wv9gC9de2JuSNnhy8/
