---
- name: restart
  become: true
  service: name=vault state=restarted

- name: Read in key
  include_vars:
    file: "~/.vault/key.json"
    name: restart_key

- name: Unseal
  uri:
    url: "{{ vault_url }}/v1/sys/unseal"
    method: PUT
    body: "{\"key\": \"{{ item }}\"}"
    body_format: json
    validate_certs: false
  with_items: "{{ restart_key.keys_base64 }}"
  tags: init
  delegate_to: 127.0.0.1
  register: unsealed

