---
- name: Add ssh key for root
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  register: backup_user_info
  become: true

- name: Add user for backups on backup server
  user:
    name: "{{ inventory_hostname }}-backup"
  become: true
  delegate_to: backup

- name: Set authorized key for backup user
  authorized_key:
    user: "{{ inventory_hostname }}-backup"
    state: present
    key: "{{ backup_user_info.ssh_public_key }}"
  become: true
  delegate_to: backup

- name: Create  directory if it does not exist
  file:
    path: "{{ backup_docker_dir }}"
    state: directory
  when: backup_docker_dir is defined

- name: Output docker logs into tmp file
  shell: "docker ps -q | xargs -L 1 docker logs > {{ backup_docker_dir }}/docker-{{ ansible_date_time.epoch }}.log"
  become: yes
  when: backup_docker_dir is defined

- name: Create target directory
  command: "ssh -oStrictHostKeyChecking=no {{ inventory_hostname }}-backup@backup.fadalax.tech mkdir -p /home/{{ inventory_hostname }}-backup{{ item }}"
  become: yes
  with_items: "{{ backup_sources }}"
  when: backup_sources is defined

- name: Backup sources
  command: "/usr/bin/rsync -e \"ssh -o StrictHostKeyChecking=no\"--delay-updates -F --compress -avzhe ssh {{ item }} {{ inventory_hostname }}-backup@backup.fadalax.tech:/home/{{ inventory_hostname }}-backup{{ item }}"
  become: yes
  with_items: "{{ backup_sources }}"
  when: backup_sources is defined

- name: Backup docker
  command: "/usr/bin/rsync -e \"ssh -o StrictHostKeyChecking=no\"--delay-updates -F --compress -avzhe ssh {{ backup_docker_dir }} {{ inventory_hostname }}-backup@backup.fadalax.tech:/home/{{ inventory_hostname }}-backup{{ backup_docker_dir }}"
  become: yes
  when: backup_docker_dir is defined
