---
- name: Install python docker module
  become: true
  package:
    name: python-docker
    state: present

- name: Create network
  docker_network:
    name: "{{ hydra_network }}"

- name: Create hydra container
  docker_container:
    name: hydra
    image: "oryd/hydra:{{ hydra_version }}"
    command: "serve all"
    restart_policy: always
    ports:
     - "9000:4444"
     - "9001:4445"
    networks:
      - name:  "{{ hydra_network }}"
    env:
      DSN: memory
      SECRETS_SYSTEM: "{{ hydra_system_secret }}"
      URLS_SELF_ISSUER: "{{ hydra_self_issuer }}"
      URLS_CONSENT: "{{ hydra_idp_url }}/consent"
      URLS_LOGIN: "{{ hydra_idp_url }}/login"
      SERVE_TLS_KEY_PATH: "/cert.key"
      SERVE_TLS_CERT_PATH: "/cert.pem"
      LOG_LEVEL: "debug"
      SERVE_PUBLIC_CORS_ENABLED: "true"
      SERVE_PUBLIC_CORS_ALLOWED_METHODS: "POST,GET,PUT,DELETE" 
      SERVE_ADMIN_CORS_ENABLED: "true"
      SERVE_ADMIN_CORS_ALLOWED_METHODS: "POST,GET,PUT,DELETE" 
      
    volumes:
      - /home/vagrant/cert.key:/cert.key
      - /home/vagrant/cert.pem:/cert.pem


- name: Wait for hydra to start
  wait_for:
    port: 9000
    delay: 5

- name: Create Client - Vault
  docker_container:
    name: hydra-exec-vault
    image: "oryd/hydra:{{ hydra_version }}"
    command: "clients create --skip-tls-verify \
    --id vault --secret test12345678 \
    --grant-types authorization_code,refresh_token,client_credentials,implicit \
    --response-types token,code,id_token \
    --scope testp,openid,offline \
    --callbacks {{ hydra_vault_url }}/ui/vault/auth/oidc/oidc/callback"
    networks:
      - name:  "{{ hydra_network }}"
    env:
      SECRETS_SYSTEM: "{{ hydra_system_secret }}"
      HYDRA_ADMIN_URL: "https://hydra:4445"

- name: Create Client - Fadalax Frontend
  docker_container:
    name: hydra-exec-fadalax-frontend
    image: "oryd/hydra:{{ hydra_version }}"
    command: "clients create --skip-tls-verify \
    --id fadalax-frontend --secret {{ hydra_fadalax_frontend_secret }} \
    --grant-types authorization_code,refresh_token,client_credentials,implicit \
    --response-types token,code,id_token \
    --scope testp,openid,offline \
    --callbacks https://fadalax.tech/index.html \
    --post-logout-callbacks https://fadalax.tech/index.html"
    networks:
      - name:  "{{ hydra_network }}"
    env:
      SECRETS_SYSTEM: "{{ hydra_system_secret }}"
      HYDRA_ADMIN_URL: "https://hydra:4445" 
