---
vault_version: "1.2.3"
vault_architecture_map:
  # this first entry seems... redundant (but it's required for reasons)
  amd64: amd64
  x86_64: amd64
  armv7l: arm
  aarch64: arm64
vault_architecture: "{{ vault_architecture_map[ansible_architecture] }}"
vault_os: "{{ ansible_system|lower }}"
vault_pkg: "vault_{{ vault_version }}_{{ vault_os }}_{{ vault_architecture }}.zip"
vault_zip_url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_{{ vault_os }}_{{ vault_architecture }}.zip"


vault_local_dir: "~/.vault/"

# should resolve from the host system
vault_url: "http://127.0.0.1:8200"
vault_ssl: false
vault_ssl_cert_folder: "/etc/certs/"
vault_ssl_cert: "/etc/certs/vault.crt" 
vault_ssl_key: "/etc/certs/vault.key" 

# base config
vault_bin_path: /usr/local/bin
vault_config_path: /etc/vault.d
vault_data_path: /var/vault
vault_main_config: "{{ vault_config_path }}/vault_main.hcl"
vault_secret_shares: "1"
vault_secret_threshold: "1"

# Vault as a Cert Authority
vault_ca: false
vault_ca_base_domain: "example.invalid" 
vault_ca_domain: "aaa.example.invalid" # needs to be the same as the base domain without the protocol and port
vault_ca_issuing: "http://127.0.0.1:8200/v1/pki/ca"
vault_ca_crl: "http://127.0.0.1:8200/v1/pki/crl"
# If set the vault url needs to be a subdomain of the base domain
vault_ca_bootstrap_ssl: false 
vault_ca_bootstrap_url: "http://127.0.0.1:8200" #Non https url that resolves during setup


vault_oidc: false
vault_oidc_url: "localhost:9000"
vault_oidc_client: "vault"
oidc_client_secret: "test12345678"
vault_oidc_rediect_uri: "http://localhost:8200/ui/vault/auth/oidc/oidc/callback"




