---
- name: Create config directory
  become: true
  file:
    dest: "{{ vault_config_path }}"
    state: directory

- name: Vault main configuration
  become: true
  template:
    src: vault-config.hcl.j2
    dest: "{{ vault_main_config }}"
    mode: "0400"
  notify: Restart vault
