---
- hosts: vault
  roles:
    - role: vault
  vars:
    vault_oidc: false

- hosts: 127.0.0.1
  connection: local
  roles:
    - role: vault_add_ca
  vars:
    vault_url: "https://vault.fadalax.tech:8200"

- hosts: hydra
  roles:
    - role: vault_issue_cert
    - role: vault_add_ca
    - role: hydra
  vars_files:
    - ./vault
  vars:
    hydra_self_issuer: "https://hydra.fadalax.tech:9000"
    hydra_idp_url: "http://idp.fadalax.tech"
    hydra_vault_url: "https://vault.fadalax.tech:8200"

- hosts: idp
  roles:
    - role: docker
    - role: vault_service_token
    - role: vault_add_ca
    - role: mysql
    - role: idp
    - role: vault_issue_cert
    - role: frontend
    - role: nginx_proxy
  vars_files:
    - ./vault
  vars:
    docker_install_compose: false
    idp_hydra_admin: "https://hydra.fadalax.tech:9001"

- hosts: vault
  roles:
    - role: vault
  vars:
    vault_oidc: true






  
